flask_bot/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_security import Security
from flask_bot.admin.admin import admin
from flask_jwt_extended import JWTManager
from .views.auth import auth, login_manager
from .model.user import user_datastore
from .config.base import Config
from .model import db
from .views.ticket import ticket


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    with app.app_context():
        db.create_all()
    migrate = Migrate(app, db)
    security = Security(app, user_datastore)
    jwt = JWTManager(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login_users'
    admin.init_app(app)

    app.register_blueprint(ticket)
    app.register_blueprint(auth)

    return app

flask_bot/admin/__init__.py
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user


class MyModelView(ModelView):
    def is_accessible(self):
        if not current_user.is_authenticated:
            return False

        for role in current_user.roles:
            if role.name == 'admin':
                return True
        return False


class MyModelViewTicket(ModelView):
    def is_accessible(self):
        if not current_user.is_authenticated:
            return False

        for role in current_user.roles:
            if role.name == 'developer':
                return True
        return False

flask_bot/model/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

flask_bot/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, session, request
from flask_jwt_extended import create_access_token
from marshmallow import ValidationError
from ..model.user import User
from ..sh.user import UserSchema

auth = Blueprint('auth', __name__, url_prefix='/auth')

user_schema = UserSchema()


@auth.route('/register', methods=['POST'])
def register():
    try:
        user_data = UserSchema().load(request.json)
    except ValidationError as e:
        return jsonify(e.messages), 400
    create_user = User(
        username=user_data['username'],
        password=user_data['password'],
        email=user_data['email'],
        token=user_data['token']
    )
    create_user.password_hash(password=user_data['password'])
    create_user.create_users(create_user)
    result = UserSchema().dump(create_user)
    return jsonify(result)


@auth.route('/sign-in', methods=['POST'])
def login():
    try:
        user_data = UserSchema().load(request.json)
    except ValidationError as e:
        return jsonify(e.messages), 400

    user = User.query.filter_by(email=user_data['email']).first()
    if user and user.check_password(user_data['password']):
        access_token = create_access_token(identity=user.id)
        return user_schema.dump(user)
    else:
        return jsonify({'login': False})


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from flask_login import login_user, LoginManager, login_required
from wtforms.validators import DataRequired, Email
login_manager = LoginManager()


class LoginForm(FlaskForm):
    email = StringField(validators=[DataRequired(), Email()])
    password = PasswordField(validators=[DataRequired()])
    submit = SubmitField()


@auth.route('/login', methods=['GET', 'POST'])
def login_users():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data, password=form.password.data).first()
        if user is not None:
            login_user(user)
            return redirect(url_for('admin.index'))

    return render_template('auth/login.html', form=form)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@auth.route('/secret')
@login_required
def secret():
    return "This is a secret page!"

flask_bot/views/ticket.py
from datetime import datetime
import pytz
from flask import Blueprint, jsonify, request
from marshmallow import ValidationError
from ..model import db
from ..model.ticket import Ticket
from ..model.user import User
from ..sh.ticket import TicketSchema
from ..sh.user import UserSchema


ticket = Blueprint('tickets', __name__, url_prefix='/api/ticket')

ticket_schema = TicketSchema(many=True)


@ticket.route('/list', methods=['GET'])
def ticket_list():
    tickets = Ticket.query.all()
    ticket_mp = TicketSchema().dump(tickets)
    return jsonify({
        'result': ticket_mp
    })


@ticket.route('/create', methods=['POST'])
def ticket_create():
    ticket_schemas = TicketSchema()
    try:
        ticket_data = ticket_schemas.load(request.json)
    except ValidationError as e:
        return jsonify(e.messages), 400

    create_ticket = Ticket(
        title=ticket_data['title'],
        user_id=ticket_data['user_id'],
        description=ticket_data['description'],
    )
    db.session.add(create_ticket)
    db.session.commit()
    ticket_schemas.dump(create_ticket)


@ticket.route('/send_date', methods=['PUT', "POST"])
def send_message():
    users = User.query.filter(User.notification_time != None).all()
    local_kz = pytz.timezone('Asia/Almaty')
    current_time = datetime.now(local_kz)
    try:
        user_data = UserSchema(only=['id', 'notification_time']).load(request.json)
    except ValidationError as e:
        return jsonify(e.messages), 400

    user_create = User(
        id=user_data['id'],
        notification_time=user_data['notification_time']
    )
    db.session.add(user_create)
    db.session.commit()
    while True:
        for user in users:
            if current_time == user_data['notification_time']:
                message = "Время оповещения наступило!"
                user.notification_time = None
                db.session.commit()

flask_bot/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
        </svg>
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
    </ul>

    {% if current_user.is_authenticated %}
    <div class="col-md-3 text-end">
            <button type="button" class="btn btn-primary"><a href="{{url_for('auth.logout')}}">Logout</a></button>
        </div>
    {% else %}
       <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2"><a href="{{url_for('auth.login')}}">Login</a></button>
        <button type="button" class="btn btn-primary"><a href="{{url_for('auth.register')}}">Sign-up</a></button>
    </div>
    {% endif %}
</header>
</div>
</body>
</html>

flask_bot/templates/ticket/ticket_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>dfsdafsaf</h1>
</body>
</html>

flask_bot/templates/ticket/ticket_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>upload message</h1>
  <form method="POST" action="">
        {{form.hidden_tag()}}
        <fieldset>
            {{form.title}}
            {{form.users_token}}
            {{form.description}}
        </fieldset>
        {{form.submit}}
    </form>
</body>
</html>